theme = "reveal-hugo"
baseURL = "https://munchiez.io/"
languageCode = "de-de"
title = "munchiez.io | Mixed Medial Arts"

[params]
customCSS = ["style.css"]

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
